<!-- ---
title: JS深入系列之手写Promise
date: 2022-10-20
tags: ES6系列, JS深入系列
set: DeepJS
--- -->

Promise是一种处理异步代码的方式，避免了JS异步处理时会陷入回调地狱的模式。我们接下来就在了解Promise基本用法的同时，逐步完成Promise的手写。

## 一. Promise的基本特点

Promise实例包含有一些状态的管理和变迁，是Promise的基础
### 1. promise的状态
Promise有两个基本特点：
* **状态不受外界影响**：`Promise`代表一个异步操作，有`pending(进行中)`、`fulfilled(已成功)`、`rejected(已失败)`三种状态。初始状态为`pending`，只有异步操作的结果可以决定当前的状态，其他任何操作都无法决定或改变这个状态
* **状态一旦改变，不会再变**：只要`Promise`的状态发生了改变，就不会再变了，会一直保持这个结果。

我们可以用`Class`来实现，定义一些静态状态，在构造函数内设置初始化状态
```javascript
class myPromise {
    // 管理静态的Promise状态
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'

    constructor() {
        // 初始状态就是pending
        this.promiseState = myPromise.PENDING
    }
}
```
### 2. resolve和reject
Promise构造函数接受一个函数作为参数，如果没有传入会报错，该函数有两个参数分别是`resolve`和`reject`，这两个函数，由`JavaScript`引擎提供，不用自己部署。
* **resolve**：将`Promise`对象的状态从`pending`转换为`fulfilled`，在异步操作成功时调用，并将异步操作的结果，作为参数传递出去
* **reject**：将`Promise`对象的状态从`pending`转换为`rejected`，在异步操作失败时调用，并将异步操作中报出的错误，作为参数传递出去。

针对这些特点，手写Promise时，我们可以在构造函数内传入执行函数作为参数，并且在`Class`中定义`Promise`的方法`resolve`和`reject`，在这两个方法中改变`Promise`的状态
```javascript
class myPromise {
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'
    constructor(fn) {
        this.promiseState = myPromise.PENDING
        fn(this.resolve, this.reject)
    } 
    resolve() {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.FULFILLED
        }
    }
    reject() {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.REJECTED
        }
    }
}
```

在原生`Promise`中，执行`resolve()`和`reject()`的时候可以传入一个参数，在Promise实例执行后就可以使用这个参数，作为回调结果。
```javascript
let promise = new Promise((resolve, reject) => {
    resolve('go')
})
```
那在手写`Promise`时，我们就可以将这个回调结果定义为`promiseResult`，在`resolve`和`reject`中将结果赋值给这个变量
```javascript
class myPromise {
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'
    constructor(fn) {
        this.promiseState = myPromise.PENDING
        this.promiseResult = null
        fn(this.resolve, this.reject)
    } 
    resolve(result) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.FULFILLED
            this.promiseResult = result
        }
    }
    reject(reason) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.REJECTED
            this.promiseResult = reason
        }
    }
}
```
写到这里，我们来直接试运行一下：
```javascript
class myPromise { ... }
let p1 = new myPromise((resolve, reject) => {
    resolve('go')
})
```
最终的输出是：
```javascript
// 报错：Uncaught TypeError: Cannot read property 'PromiseState ' of undefined
```
会发现，我们的`resolve`和`reject`在执行的时候，`this`已经丢了，所以会导致`constructor`定义的`promiseState`变成了`undefined`。原因是我们`new`一个新实例的时候执行的是`constructor`里面的内容，`constructor`里面的`this`确实是新实例的，但现在我们是在实例被创建后，调用`resolve`方法的，不是在`class`内部执行的，因此会报错。这里我们做个修正，给`resolve`和`reject`方法绑定`this`为当前实例
```javascript
class myPromise {
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'
    constructor(fn) {
        this.promiseState = myPromise.PENDING
        this.promiseResult = null
        fn(this.resolve.bind(this), this.reject.bind(this))
    } 
    resolve(result) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.FULFILLED
            this.promiseResult = result
        }
    }
    reject(reason) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.REJECTED
            this.promiseResult = reason
        }
    }
}
```
测试一下我们的手写promise
```javascript
// 测试代码
let p1 = new myPromise((resolve, reject) => {
    resolve('go');
})
console.log(p1); 
// myPromise {PromiseState: 'fulfilled', PromiseResult: 'go'}
```
<img src="https://zhangmingemma.github.io/dist/images/2022-10-20/1.png" style="display:inline-block; margin-bottom:16px; width:500px;">

### 3. 执行异常

执行异常就是，在谈到`reject`的时候，有说**在异步操作失败时调用reject，并将异步操作中报出的错误，作为参数传递出去**。因此我们在手写Promise中，就可以在执行函数的时候用`try/catch`包起来，`catch`方法内调用`reject`

```javascript
class myPromise {
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'
    constructor(fn) {
        this.promiseState = myPromise.PENDING
        this.promiseResult = null
        try {
            fn(this.resolve.bind(this), this.reject.bind(this))
        } catch(e) {
            this.reject(e)
        }
    } 
    resolve(result) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.FULFILLED
            this.promiseResult = result
        }
    }
    reject(reason) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.REJECTED
            this.promiseResult = reason
        }
    }
}
```
我们来测试一下，在`Promise`中抛出异常
```javascript
class myPromise { ... }
let p1 = new myPromise((resolve, reject) => {
    throw new Error('there is an error')
})
console.log(p1)
```

<img src="https://zhangmingemma.github.io/dist/images/2022-10-20/3.png" style="display:inline-block; margin-bottom:16px; width:500px;">

## 二. then

then创建实例后再进行调用的，是在`Promise`原型对象上定义的方法

### 1. then基本实现

then是在`Promise`实例状态发生改变时的回调函数。`then`接受两个函数作为参数，这两个参数是可选的。
* **第一个回调是resolve后调用的**：将`resolve`传出的参数作为这个函数的参数
* **第二个回调是reject后调用的**：将`reject`传出的参数作为这个函数的参数

已知这些之后，我们将then的两个参数分别定义为`onFulfilled`、`onRejected`，`onFulfilled`是在`resolve`之后执行的，也就是状态时`fulfilled`时执行，同样的`onRejected`是在`rejected`状态时执行的。我们之前得到的回调结果`promiseResult`作为`onFulfilled`和`onRejected`的参数
```javascript
class myPromise {
    ...
    then(onFulfilled, onRejected) {
        if (this.promiseState == myPromise.FULFILLED) {
            onFulfilled(this.promiseResult)
        }
        if (this.promiseState == myPromise.REJECTED) {
            onRejected(this.promiseResult)
        }
    }
}
```
执行测试代码
```javascript
class myPromise {...}
let p1 = new myPromise((resolve, reject) => {
    resolve('go')
    reject('reject')
})
p1.then(
    res => {
        console.log(res)
    },
    rea => {
        console.log(rea)
    }
)
```
执行结果
```javascript
go
```

可以看到，我们在`resolve`执行之后，状态改变为`fulfilled`，执行`then`第一个参数的函数，之后的`reject`方法就没有再执行了，这也印证了我们最开始提到的`Promise`的**状态一旦被改变，就不会发生二次修改**。

### 2. then参数校验

**Promise的`then`方法，两个参数如果不是函数的话就要被忽略。**忽略并不是什么都不做，而是将最后的结果原封不动的返回。
```javascript
let p1 = new Promise((resolve, reject) => {
    throw new Error('reject')
})
p1.then(undefined, reason => { console.log('rejected:', reason) })
//rejected: Error: reject
```
原生`Promise`不会有报错，可以顺利执行，因此，我们需要对`then`的参数进行校验
```javascript
class myPromise {
    ...
    then(onFulfilled, onRejected) {
        onFulfilled = typeof onFulfilled == 'function'
            ? onFulfilled
            : value => value
        onRejected = typeof onRejected == 'function'
            ? onRejected
            : reason => { throw reason }
        if (this.promiseState == myPromise.FULFILLED) {
            onFulfilled(this.promiseResult)
        }
        if (this.promiseState == myPromise.REJECTED) {
            onRejected(this.promiseResult)
        }
    }
}
```

## 三. 实现异步

Promise最主要的就是异步能力，Promise的执行顺序有以下几个特点：
* **Promise会立即执行**
* **Promise的`then`会加入微任务队列**，全局逻辑执行结束之后，再逐次执行
* **Promise的`then`会判断实例状态，如果处于pending状态，会将回调函数加入执行队列，等到状态变化后，继续执行**

```javascript
console.log(1);
let promise1 = new Promise((resolve, reject) => {
    console.log(2);
    resolve('这次一定');
})
promise1.then(
    result => {
        console.log('fulfilled:', result);
    },
    reason => {
        console.log('rejected:', reason)
    }
)
console.log(3);
```
<img src="https://zhangmingemma.github.io/dist/images/2022-10-20/4.png" style="display:inline-block; margin-bottom:16px; width:500px;">

可以看到Promise.then中是存在异步执行的，因此我们再手写的Promise需要加入异步操作
```javascript
class myPromise {
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'
    constructor(fn) {
        this.promiseState = myPromise.PENDING
        this.promiseResult = null
        try {
            fn(this.resolve.bind(this), this.reject.bind(this))
        } catch(e) {
            this.reject(e)
        }
    } 
    resolve(result) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.FULFILLED
            this.promiseResult = result
        }
    }
    reject(reason) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.REJECTED
            this.promiseResult = reason
        }
    }
    then(onFulfilled, onRejected) {
        onFulfilled = typeof onFulfilled == 'function'
            ? onFulfilled
            : value => value
        onRejected = typeof onRejected == 'function'
            ? onRejected
            : reason => { throw reason }
        if (this.promiseState == myPromise.FULFILLED) {
            setTimeout(() => {
                onFulfilled(this.promiseResult)
            })
        }
        if (this.promiseState == myPromise.REJECTED) {
            setTimeout(() => {
                onRejected(this.promiseResult)
            })
        }
    }
}
```
我们来测试一下`myPromise`的执行顺序，是否和原生`Promise`的执行顺序一致。测试之后和原生promise的执行顺序一致
```javascript
console.log(1);
let promise1 = new myPromise((resolve, reject) => {
    console.log(2);
    resolve('这次一定');
})
promise1.then(
    result => {
        console.log('fulfilled:', result);
    },
    reason => {
        console.log('rejected:', reason)
    }
)
console.log(3);
```
那对于更复杂的情况，`resolve`内添加`setTimeout`，使得`resolve`也异步执行，那和`then`一起异步，究竟是谁先会被调用？
```javascript
console.log(1);
let promise1 = new Promise((resolve, reject) => {
    console.log(2);
    setTimeout(() => {
        resolve('这次一定');
        console.log(4)
    })
})
promise1.then(
    result => {
        console.log('fulfilled:', result);
    },
    reason => {
        console.log('rejected:', reason)
    }
)
console.log(3);
```
<img src="https://zhangmingemma.github.io/dist/images/2022-10-20/5.png" style="display:inline-block; margin-bottom:16px; width:500px;">

这里我们分析整个逻辑运行：
* 顺次执行逻辑`console.log(1)`
* `Promise`的执行函数会立刻执行，顺次执行逻辑`console.log(2)`
* 遇到`setTimeout`之后，将`setTimeout`内的执行函数加入**宏任务队列**
* 遇到`then`之后，将`then`内的执行函数加入**微任务队列**
* 顺次执行逻辑`console.log(3)`
* 全部顺次逻辑执行后，再执行微任务，即`then`的执行函数。但注意！此时我们`Promise`的状态仍旧是`pending`，因此无法执行`then`中的函数
* 再执行宏任务`setTimeout`中的执行函数，那我们看最终的结果来看是先执行`console.log(4)`再执行`resolve`的输出，那说明在原生`Promise`中，**resolve也是一个异步的执行**，其次是**resolve之后还也可以执行回调函数**

因此，我们在手写`Promise`的`resolve`中也要加上 **resolve也是一个异步的执行**，**resolve之后还也可以执行回调函数**这两个点。因此，就是 **then判断Promise的状态为pending的时候，就把回调函数添加到回调函数组，在执行到resolve之后，异步将回调函数组内函数再执行**。同样的逻辑也适用于`reject`
```javascript
class myPromise {
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'
    constructor(fn) {
        this.promiseState = myPromise.PENDING
        this.promiseResult = null
        this.onFulfilledCallbacks = [] // 保存成功回调
        this.onRejectedCallbacks = []  // 保存失败回调
        try {
            fn(this.resolve.bind(this), this.reject.bind(this))
        } catch(e) {
            this.reject(e)
        }
    } 
    resolve(result) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.FULFILLED
            this.promiseResult = result
            // 执行回调队列中的函数
            this.onFulfilledCallbacks.forEach(callback => {
                callback(result)
            })
        }
    }
    reject(reason) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.REJECTED
            this.promiseResult = reason
            // 执行回调队列中的函数
            this.onRejectedCallbacks.forEach(callback => {
                callback(reason)
            })
        }
    }
    then(onFulfilled, onRejected) {
        onFulfilled = typeof onFulfilled == 'function'
            ? onFulfilled
            : value => value
        onRejected = typeof onRejected == 'function'
            ? onRejected
            : reason => { throw reason }
        if (this.promiseState == myPromise.FULFILLED) {
            setTimeout(() => {
                onFulfilled(this.promiseResult)
            })
        }
        if (this.promiseState == myPromise.REJECTED) {
            setTimeout(() => {
                onRejected(this.promiseResult)
            })
        }
        // 判断pending状态，将异步的执行函数加入执行队列
        if (this.promiseState == myPromise.PENDING) {
            this.onFulfilledCallbacks.push(() => {
                setTimeout(() => {
                    onFulfilled(this.promiseResult)
                })   
            })
            this.onRejectedCallbacks.push(() => {
                setTimeout(() => {
                    onRejected(this.promiseResult)
                })   
            })
        }
    }
}
```
我们来进行一下测试，看看最终的输出结果是和原生`Promise`的输出结果相同
```javascript
console.log(1);
let promise1 = new myPromise((resolve, reject) => {
    console.log(2);
    setTimeout(() => {
        resolve('这次一定');
        console.log(4)
    })
})
promise1.then(
    result => {
        console.log('fulfilled:', result);
    },
    reason => {
        console.log('rejected:', reason)
    }
)
console.log(3);
```

## 四. then链式调用

我们知道`Promise`最厉害的点就是可以实现`链式调用`，解决回调地狱。
* **then返回一个Promise实例**
* **then可以实现链式调用**，将第一层resolve可以传递给下一层执行

举个简单的链式调用的例子
```javascript
let p1 = new Promise((resolve, reject) => {
    resolve(100)
})
p1.then(res => {
    console.log('fulfilled', res);
    return 2 * res
}).then(res => {
    console.log('fulfilled', res)
})
```
最终的输出
```
fulfilled 100
fulfilled 200
```
### 1. then返回一个Promise实例
我们来实现手写`Promise`这一部分，首先是**then返回一个Promise实例**
```javascript
class myPromise {
    ...
    then(onFulfilled, onRejected) {
        onFulfilled = typeof onFulfilled == 'function'
            ? onFulfilled
            : value => value
        onRejected = typeof onRejected == 'function'
            ? onRejected
            : reason => { throw reason }
        const promise = new myPromise((resolve, reject) => {
            if (this.promiseState == myPromise.FULFILLED) {
                setTimeout(() => {
                    onFulfilled(this.promiseResult)
                })
            }
            if (this.promiseState == myPromise.REJECTED) {
                setTimeout(() => {
                    onRejected(this.promiseResult)
                })
            }
            // 判断pending状态，将异步的执行函数加入执行队列
            if (this.promiseState == myPromise.PENDING) {
                this.onFulfilledCallbacks.push(() => {
                    setTimeout(() => {
                        onFulfilled(this.promiseResult)
                    })   
                })
                this.onRejectedCallbacks.push(() => {
                    setTimeout(() => {
                        onRejected(this.promiseResult)
                    })   
                })
            }
        })
        return promise
    }
}
```
### 2. Promise的冒泡
其次，就是**then的返回结果传递给下一层then**，这里实现上我们用一个封装的函数来处理下一层的`resolve`和`reject`。这里我们封装一个`resolvePromise`函数来做这件事情。额外需要注意的是，**Promise对象的错误是具有`冒泡`性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个`catch`语句捕获。Catch方法也会返回一个Promise对象，因此后面还可以继续调用`then`方法。**
```javascript
class myPromise {
    ...
    then(onFulfilled, onRejected) {
        const promise = new myPromise((resolve, reject) => {
            if (this.promiseState == myPromise.FULFILLED) {
                setTimeout(() => {
                    try {
                        if (typeof onFulfilled != 'function') {
                            resolve(this.promiseResult)
                        } else {
                            const x = onFulfilled(this.promiseResult)
                            resolvePromise(promise, x, resolve, reject)
                        }
                    } catch(e) {
                        // 接收抛出的异常
                        reject(e)
                    }
                })
            }
            if (this.promiseState == myPromise.REJECTED) {
                setTimeout(() => {
                    try {
                        if (typeof onRejected != 'function') {
                            reject(this.promiseResult)
                        } else {
                            const x = onRejected(this.promiseResult)
                            resolvePromise(promise, x, resolve, reject)
                        }
                    } catch(e) {
                        // 接收抛出的异常
                        reject(e)
                    }
                })
            }
            // 判断pending状态，将异步的执行函数加入执行队列
            if (this.promiseState == myPromise.PENDING) {
                this.onFulfilledCallbacks.push(() => {
                    setTimeout(() => {
                        try {
                            if (typeof onFulfilled != 'function') {
                                resolve(this.promiseResult)
                            } else {
                                const x = onFulfilled(this.promiseResult)
                                resolvePromise(promise, x, resolve, reject)
                            }
                        } catch(e) {
                            // 接收抛出的异常
                            reject(e)
                        }
                    }) 
                })
                this.onRejectedCallbacks.push(() => {
                    setTimeout(() => {
                        try {
                            if (typeof onRejected != 'function') {
                                reject(this.promiseResult)
                            } else {
                                const x = onRejected(this.promiseResult)
                                resolvePromise(promise, x, resolve, reject)
                            }
                        } catch(e) {
                            // 接收抛出的异常
                            reject(e)
                        }
                    })
                })
            }
        })
        return promise
    }
}
function resolvePromise(promise, x, resolve, reject) {}
```

那接下来就是如何去封装resolvePromise，让resolve和reject
```javascript
function resolvePromise(promise, x, resolve, reject) {
    if (x instanceof myPromise) {
        // 如果x也是一个promise实例，那就让promise接收x的状态，继续执行
        x.then(y => {
            resolvePromise(promise, y, resolve, reject)
        }, reject)
    } else if ( x != null && (typeof x == 'object' || typeof x == 'function')) {
        // 如果x是一个执行函数，或是一个值，那就直接执行then
        const then = x.then
        if (typeof then == 'function') {
            try {
                then.call(
                    x,
                    y => {
                        resolvePromise(promise, y, resolve, reject)
                    },
                    r => {
                        reject(r)
                    }
                )
            } catch(e) {
                reject(e)
            }
        } else {
            resolve(x)
        }
    } else {
        return resolve(x)
    }
}

```
基于此，我们再给出一个示例来测试
```javascript
const p2 = new myPromise((resolve, reject) => {
    resolve(100)
})

p2.then(res => {
    console.log('fulfilled', res);
    return new myPromise((resolve, reject) => resolve(3 * res))
}).then(res => {
    console.log('fulfilled', res)
})
```
最终输出，可以看到可以最终实现链式调用
```javascript
fulfilled 100
fulfilled 300
```

给出，我们最终的Promise的代码
```javascript
class myPromise {
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'
    constructor(fn) {
        this.promiseState = myPromise.PENDING
        this.promiseResult = null
        this.onFulfilledCallbacks = [] // 保存成功回调
        this.onRejectedCallbacks = []  // 保存失败回调
        try {
            fn(this.resolve.bind(this), this.reject.bind(this))
        } catch(e) {
            this.reject(e)
        }
    } 
    resolve(result) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.FULFILLED
            this.promiseResult = result
            // 执行回调队列中的函数
            this.onFulfilledCallbacks.forEach(callback => {
                callback(result)
            })
        }
    }
    reject(reason) {
        if (this.promiseState == myPromise.PENDING) {
            this.promiseState = myPromise.REJECTED
            this.promiseResult = reason
            // 执行回调队列中的函数
            this.onRejectedCallbacks.forEach(callback => {
                callback(reason)
            })
        }
    }
    then(onFulfilled, onRejected) {
        const promise = new myPromise((resolve, reject) => {
            if (this.promiseState == myPromise.FULFILLED) {
                setTimeout(() => {
                    try {
                        if (typeof onFulfilled != 'function') {
                            resolve(this.promiseResult)
                        } else {
                            const x = onFulfilled(this.promiseResult)
                            resolvePromise(promise, x, resolve, reject)
                        }
                    } catch(e) {
                        // 接收抛出的异常
                        reject(e)
                    }
                })
            }
            if (this.promiseState == myPromise.REJECTED) {
                setTimeout(() => {
                    try {
                        if (typeof onRejected != 'function') {
                            reject(this.promiseResult)
                        } else {
                            const x = onRejected(this.promiseResult)
                            resolvePromise(promise, x, resolve, reject)
                        }
                    } catch(e) {
                        // 接收抛出的异常
                        reject(e)
                    }
                })
            }
            // 判断pending状态，将异步的执行函数加入执行队列
            if (this.promiseState == myPromise.PENDING) {
                this.onFulfilledCallbacks.push(() => {
                    setTimeout(() => {
                        try {
                            if (typeof onFulfilled != 'function') {
                                resolve(this.promiseResult)
                            } else {
                                const x = onFulfilled(this.promiseResult)
                                resolvePromise(promise, x, resolve, reject)
                            }
                        } catch(e) {
                            // 接收抛出的异常
                            reject(e)
                        }
                    }) 
                })
                this.onRejectedCallbacks.push(() => {
                    setTimeout(() => {
                        try {
                            if (typeof onRejected != 'function') {
                                reject(this.promiseResult)
                            } else {
                                const x = onRejected(this.promiseResult)
                                resolvePromise(promise, x, resolve, reject)
                            }
                        } catch(e) {
                            // 接收抛出的异常
                            reject(e)
                        }
                    })
                })
            }
        })
        return promise
    }
}
function resolvePromise(promise, x, resolve, reject) {
    if (x instanceof myPromise) {
        // 如果x也是一个promise实例，那就让promise接收x的状态，继续执行
        x.then(y => {
            resolvePromise(promise, y, resolve, reject)
        }, reject)
    } else if ( x != null && (typeof x == 'object' || typeof x == 'function')) {
        // 如果x是一个执行函数，或是一个值，那就直接执行then
        try {
            const then = x.then
        } catch(e) {
            return reject(e)
        }
        if (typeof then == 'function') {
            let called = false // 避免多次调用
            try {
                then.call(
                    x,
                    y => {
                        if(called) return
                        called = true
                        resolvePromise(promise, y, resolve, reject)
                    },
                    r => {
                        if (called) return 
                        called = true
                        reject(r)
                    }
                )
            } catch(e) {
                if (called) return 
                called = true
                reject(e)
            }
        } else {
            resolve(x)
        }
    } else {
        return resolve(x)
    }
}
```

## 五. Promise的其他方法

### 1. Promise.all

Promise.all是ES6对象上的一个方法，它的功能是将多个`Promise`实例包装成一个`Promise`实例
* **返回值是一个promise实例**
* **接收一个可遍历的数据容器，每个元素都是promise实例**，那如果不是promise实例，就会将其转换为promise实例之后再实现
* **数组中每个实例都成功，promise.all才成功，所有resolve结果是promise.all的resolve结果**
* **数组中任一实例失败，promise.all就失败，第一个reject结果就是promise.all的reject结果**

因此我们的手动实现就是
```javascript
Promise.prototype._all = function(promises) {
    let resArr = [], count = 0
    return new Promise((resolve, reject) => {
        promises.forEach((item, index) => {
            Promise.resolve(item).then(res => {
                resArr[index] = res
                count += 1
                if (count == promises.length) resolve(resArr)
            }).catch(reject)
        })
    })
}
```

### 2. Promise.any

Promise.all是ES6对象上的一个方法，它的功能是将多个`Promise`实例包装成一个`Promise`实例
* **返回值是一个promise实例**
* **接收一个可遍历的数据容器，每个元素都是promise实例**，那如果不是promise实例，就会将其转换为promise实例之后再实现
* **数组中任一实例成功，promise.any就成功，第一个resolve结果是promise.any的resolve结果**
* **数组中全部实例失败，promise.any就失败，reject结果是AggregateError**

```javascript
Promise.prototype._any = function(promises) {
    let resArr = [], count = 0
    return new Promise((resolve, reject) => {
        promises.forEach((item, index) => {
            Promise.resolve(item).then(resolve).catch(e) {
                count += 1
                if (count == promises.length) reject('AggregateError')
            }
        })
    })
}
```

### 3. Promise.race

不论成功与否，第一个Promise的结果就是Promise.race的结果，不论成功与否
```javascript
Promise.prototype._race = function(promises) {
    return new Promise((resolve, reject) => {
        promises.forEach((item, index) => {
            Promise.resolve(item).then(resolve).catch(reject)
        })
    })
}
```

### 4. Promise.allSettled

所有Promise实例全部执行完之后再执行下一步操作
```javascript
Promise.prototype._allSettled = function(promises) {
    let resArr = [], count += 0
    return new Promise((resolve, reject) => {
        promises.forEach((item, index) => {
            Promise.resolve(item).then(res => {
                resArr[index] = {status:'fulfilled', value:res}
                count += 1
                if (count == promises.length) resolve(resArr)
            }).catch(e => {
                resArr[index] = {status:'rejected', value: e}
                count += 1
                if (count == promises.length) resolve(resArr)
            })
        })
    })
}
```





